### ISSUE TITLE
How to get session data the right way?

### ISSUE THREAD

**Issue by MartinMalinda** [jamesdixon/ember-cli-simple-auth-firebase#4]
What is the proper way to access session data about the authenticated user?

I could only retrieve the data under a path like this: session.secure.password.email, which looks a bit awkward and it works only after fresh login, not after restored login from saved token.

Is there any solution to this I am missing or am I supposed to write my own code to solve this?

**Comment by jamesdixon** [comment]
Hi, you'll need to create a custom session by extending `SimpleAuth.Session`. Here's an example: 

``` js
import Ember from 'ember';
import Session from 'simple-auth/session';

export default Session.extend({
  currentUser: function() {
    var uid = this.get('secure.user.id');
    if (!Ember.isEmpty(uid)) {
      return this.container.lookup('store:main').find('employee', uid);
    }
  }.property('secure.user.id')
});
```

You can find more details on `SimpleAuth.Session` [here](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-Session).

**Comment by MartinMalinda** [comment]
Exactly what I needed. Thank you!

**Comment by jamesdixon** [comment]
No problem. Good luck!
