### ISSUE TITLE
[Proposal] Allow OAuth providers

### ISSUE THREAD

**Issue by rtablada** [jamesdixon/ember-cli-simple-auth-firebase#6]
I'm currently working on a branch to allow OAuth provider support (heavily borrowed from the Firebase Torii lib).

Just a heads up, I should have a PR inbound by EOD today.

**Comment by jamesdixon** [comment]
@rtablada sounds great. let me know when you have it ready! thanks

**Comment by jamesdixon** [comment]
@rtablada did you happen to look at #5? I was just waiting on @msdedwards to implement some tests before i merged.
