### ISSUE TITLE
Instances of "simple-auth" need to be replaced with "ember-simple-auth" to be compatible with ember-simple-auth v1.0+

### ISSUE THREAD

**Issue by notmessenger** [jamesdixon/ember-cli-simple-auth-firebase#7]
I was going to make a PR for these changes but I'm not sure what other changes might need or want to be made for the upgrade to ember-simple-auth v1.0+

http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10

https://github.com/jamesdixon/ember-cli-simple-auth-firebase/blob/master/app/authenticators/firebase.js#L1

https://github.com/jamesdixon/ember-cli-simple-auth-firebase/blob/master/app/initializers/firebase-auth.js#L5

**Comment by jamesdixon** [comment]
@notmessenger I'm no longer using the addon, so I can't say what is or what isn't needed. That said, I'd be more than willing to accept a PR.
